### ISSUE TITLE
Add constraint in username TextField

### ISSUE THREAD

**Issue by hashirshoaeb** [hashirshoaeb/star_book#103]
- [x] Allow max 20 char to add for username in [UsernameAddSheet](https://github.com/hashirshoaeb/star_book/blob/master/lib/screens/username_add_sheet.dart)
- [x] Restrict user to add at least one character before continue in [UsernameAddSheet](https://github.com/hashirshoaeb/star_book/blob/master/lib/screens/username_add_sheet.dart).

You can learn from: https://api.flutter.dev/flutter/cupertino/CupertinoTextField/CupertinoTextField.html

**Comment by ShrutiJ-01** [comment]
I would like to work on this!

**Comment by cyber-venom003** [comment]
Lemme work on this

**Comment by hashirshoaeb** [comment]
@cyber-venom003 complete the previously assigned task first 😅

**Comment by spiderxm** [comment]
assign me this issue

**Comment by hashirshoaeb** [comment]
@spiderxm already assigned you, the code comment issue.

**Comment by spiderxm** [comment]
I want to work on both issues
