### ISSUE TITLE
Add Code Comments

### ISSUE THREAD

**Issue by hashirshoaeb** [hashirshoaeb/star_book#104]
Add code comments for:

- [x] Year widget
- [x] AlertDialog widget
- [x] YearPage
- [x] UsernameAddSheet
- [x] User
- [x] UnsplashPhoto
- [x] UnsplashAPIService

Take example from other classes. Learn more from here: https://dart.dev/guides/language/effective-dart/documentation

**Comment by spiderxm** [comment]
assign me this issue, i want to work on this

**Comment by hashirshoaeb** [comment]
You may have noticed that the code is well commented. With the start of SWOC, there are many classes added, but are not documented well. You just need to understand the functionality of class and static methods, and write 'code comments' above them.

For example:

```dart
/// Activity Add and Edit Sheet Screen widget.
///
/// Input form to create update and delete [Activity]
class ActivityEditSheet extends StatefulWidget {
```
```dart
  /// Adds mock data for [Activity]s in the, `Hive box` (For testing purpose only)
  ///
  /// If you think it as relational database,
  /// It populates the [activityBoxName] Table by creating new rows
  /// for each [Activity] of mock data if [activityBoxName] Table is empty
  static Future<void> initialize() async {
    Map<String, Activity> existingActivities = readAll();
    if (existingActivities.isEmpty) {
      mActivityList.forEach((Activity activity) async {
        await create(activity);
      });
    }
  }
```

I have talked to @Imadarshsri before you for this issue. But considering 'comment-first' rule of SWOC, I'm assigning this to you.

 Note: please follow the documentation guide: https://dart.dev/guides/language/effective-dart/documentation
