### ISSUE TITLE
Add mock data

### ISSUE THREAD

**Issue by hashirshoaeb** [hashirshoaeb/star_book#105]
Add mock Activity data in [mActivityList](https://github.com/hashirshoaeb/star_book/blob/master/lib/models/activity.dart#L117) from December 2020 onward dates.

Note: avoid filling activity with lorem ipsum text. Write some real type diary text, including words that express emotions like 'happy, glad, sad' etc. we will be needing this in future.

**Comment by KhyatiSaini** [comment]
Sir, I would like to work on this, please assign me this issue
