### ISSUE TITLE
Fix code to make month and year visible

### ISSUE THREAD

**Issue by spiderxm** [hashirshoaeb/star_book#107]
Add Background behind Year and Month Detail To make it visible irrespective of background image color.

<img src="https://user-images.githubusercontent.com/53966291/104415633-5ab2f680-5598-11eb-9680-82ecf8bcb28a.jpg" alt="" width="200" >

**Comment by hashirshoaeb** [comment]
One nice way is to use dark coloured image, for dark mode.

**Comment by cyber-venom003** [comment]
@hashirshoaeb Is this issue still unsolved, if yes, please assign it to me.

**Comment by hashirshoaeb** [comment]
@cyber-venom003 It's on pending. As it is depending on #121

**Comment by hashirshoaeb** [comment]
dependent on #163

**Comment by hashirshoaeb** [comment]
Fix:
Based on the brightness option,

if the brightness is light, set a light colored image,
if the brightness is dark, set a dark colored image,

**Comment by KhyatiSaini** [comment]
Sir, I would like to work on this, please assign me this issue.
