### ISSUE TITLE
Set Device Orientation

### ISSUE THREAD

**Issue by hashirshoaeb** [hashirshoaeb/star_book#118]
Set the device orientation to portrait up in main.

You can learn from here: https://api.flutter.dev/flutter/services/SystemChrome/setPreferredOrientations.html
https://api.flutter.dev/flutter/services/DeviceOrientation-class.html

Also add this limitation in code comments, that it wont work for iPad when multitasking is enabled.

**Comment by cyber-venom003** [comment]
Please assign this to me. 😄
