### ISSUE TITLE
Fixing the image in preference sheet.

### ISSUE THREAD

**Issue by ShahzadUmarBaig** [hashirshoaeb/star_book#12]
I can add a circular avatar in preference sheet in front of about developer compatible with Apple Guidelines and will be following Material UI for android devices as well.

**Comment by hashirshoaeb** [comment]
Hi, 
Sure, just don't go for Mater UI for now. Implement this only using Cupertino and Apple Guidelines. 
And use mock Github API to fetch avatar image.

**Comment by hashirshoaeb** [comment]
Use this `https://avatars0.githubusercontent.com/u/35165481?s=88` for avatar. To change size you can change the value of `s`.
Take a look into this https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/circle_avatar.dart as well.

Happy coding :)

**Comment by ShahzadUmarBaig** [comment]
I have created the circular avatar from scratch in Cupertino, will use this network image.
