### ISSUE TITLE
Fadein affect for backgrounnd images

### ISSUE THREAD

**Issue by hashirshoaeb** [hashirshoaeb/star_book#121]
Need to add fading affect for background images. 
We are using Unsplash APIs to to get wallpapers for background. 
You can use [FadeInImage](https://flutter.dev/docs/cookbook/images/fading-in-images) Widget to achieve this task. Unsplash API returns the image url and blur_hash. You are required to use blur_hash for placeholder image.

You can learn from: 
- https://unsplash.com/documentation
- https://github.com/justacid/blurhash-dart 
- https://github.com/woltapp/blurhash
- https://blurha.sh/

**Comment by Imadarshsri** [comment]
I will do it.
