### ISSUE TITLE
Add option to copy text in activityPage

### ISSUE THREAD

**Issue by hashirshoaeb** [hashirshoaeb/star_book#126]
Add an option to copy activity text in activityPage, and save it clipboard. 

You can learn from 
- https://api.flutter.dev/flutter/services/Clipboard-class.html
- https://www.youtube.com/watch?v=ZSU3ZXOs6hc
- https://api.flutter.dev/flutter/material/SelectableText-class.html

**Comment by KhyatiSaini** [comment]
Sir, I would like to work on this, please assign me this issue.
