### ISSUE TITLE
Add Code Comments

### ISSUE THREAD

**Issue by hashirshoaeb** [hashirshoaeb/star_book#127]
You may have noticed that the code is well commented. You just need to understand the functionality of class and static methods, and write 'code comments' above them.

- [x] controllers/global_setting.dart take example from other classes
- [x] models/global_setting.dart
- [x] screens/profile_page.dart

Learn more from here: https://dart.dev/guides/language/effective-dart/documentation

**Comment by spiderxm** [comment]
assign me this issue
