### ISSUE TITLE
Add TimePicker for PreferenceSheet

### ISSUE THREAD

**Issue by hashirshoaeb** [hashirshoaeb/star_book#132]
Need to implement Cupertino style time picker, to set time for reminder.
e.g.
A container in preference sheet 
`Daily Reminder      13:00 >`
 on tap => navigate to timepicker sheet
and return the selected time.
You can save the time in DateTime object.

For reference you can see how we have implemented datepicker
lib/screens/date_picker_sheet.dart and  lib/screens/activity_edit_sheet.dart

**Comment by spiderxm** [comment]
Assign me this issue
