### ISSUE TITLE
Refactor Date Picker Sheet Widget 

### ISSUE THREAD

**Issue by cyber-venom003** [hashirshoaeb/star_book#133]
![datePickWidget](https://user-images.githubusercontent.com/58390399/104832554-dfaf5000-58b7-11eb-85c5-f7d88382c2b9.PNG)

DatePickerSheet widget needs to be refactored to remove above warnings.

References : 
- https://stackoverflow.com/questions/54707731/this-class-inherits-from-a-class-marked-as-immutable-and-therefore-should-be-i
- https://api.flutter.dev/flutter/widgets/StatefulWidget-class.html
- https://stackoverflow.com/questions/58400001/should-i-call-super-initstate-at-the-end-or-at-the-beginning

**Comment by hashirshoaeb** [comment]
<img width="716" alt="Screenshot 2021-01-17 at 11 14 17 AM" src="https://user-images.githubusercontent.com/35165481/104832744-264f7b00-58b5-11eb-9da3-ed169e03821e.png">


Referance:
https://dart-lang.github.io/linter/lints/unnecessary_brace_in_string_interps.html

**Comment by spiderxm** [comment]
assign me this issue, I want to work on this issue
