### ISSUE TITLE
Daily Recommendations Implementations

### ISSUE THREAD

**Issue by SinghShreya05** [hashirshoaeb/star_book#138]
@hashirshoaeb Kindly assign me this issue under SWOC.

**Comment by TanweerulHaque** [comment]
Hey @hashirshoaeb Can you assign me this issue with @SinghShreya05  ?? I have a lot of ideas for daily recommendations ex - music, quotes etc which I think can be integrated in the application. Can I also work ?? If you all @SinghShreya05 and @hashirshoaeb you all are comfortable with this.

**Comment by hashirshoaeb** [comment]
Sure you can, if @SinghShreya05 agrees on it.

**Comment by SinghShreya05** [comment]
Yes Sir, it's fine with me. If he has already worked on it, it'll be a plus point. @hashirshoaeb

**Comment by hashirshoaeb** [comment]
@TanweerulHaque can you please ping me on slack.
