### ISSUE TITLE
Profile Page UI Designing

### ISSUE THREAD

**Issue by kanishkaa24** [hashirshoaeb/star_book#149]

**Comment by hashirshoaeb** [comment]
<img src="https://user-images.githubusercontent.com/35165481/105872713-844e3200-601c-11eb-82ac-060e53aa214a.png" alt="Star book profile page UI light mode" width="200" >

**Comment by hashirshoaeb** [comment]
<img src="https://user-images.githubusercontent.com/35165481/105872725-887a4f80-601c-11eb-9af4-afe645c231fa.png" alt="Star book profile page UI dark mode" width="200" >

**Comment by hashirshoaeb** [comment]
Solves in https://github.com/hashirshoaeb/star_book/commit/03414b7d3c25dfc2d5959c3974eb908c5a2e9bd4
