### ISSUE TITLE
Convert functions to stateless class

### ISSUE THREAD

**Issue by hashirshoaeb** [hashirshoaeb/star_book#154]
Functions that return widgets, needs to be converted into stateless class.

For more, learn from here. https://stackoverflow.com/questions/53234825/what-is-the-difference-between-functions-and-classes-to-create-reusable-widgets

**Comment by cyber-venom003** [comment]
Please assign it to me, I'll work on this.

**Comment by KhyatiSaini** [comment]
sir, please assign me this issue
