### ISSUE TITLE
Save Brightness option in hive

### ISSUE THREAD

**Issue by hashirshoaeb** [hashirshoaeb/star_book#160]
On changing the dark mode option in preference sheet, save it in have.
You need to use global settings controller. 

To initially get the option from hive
```
GlobalSettingController.getBrightnessOption()  
```
To set the brightness
```
GlobalSettingController.setbrightnessOption(option)
```

**Comment by KhyatiSaini** [comment]
Sir, please assign me this issue

**Comment by hashirshoaeb** [comment]
there was a bug in the code which is fixed now. (if you get any error, try deleting the app and building it again)
