### ISSUE TITLE
Brightness option Light/dark

### ISSUE THREAD

**Issue by hashirshoaeb** [hashirshoaeb/star_book#163]
Change the brightness of the app, on changing the dark mode option in preference sheet.

Get the brightnessOption from globalsetting controller. 

If `BrightnessOpton.auto`, get the system brightness. Retrieve the system brightness using
```
MediaQuery.of(context).platformBrightness;
```
If `BrightnessOption.light`, set
```
c.CupertinoApp(
      initialRoute: '/username_add',
      title: "StarBook",
      theme: c.CupertinoThemeData(brightness: Brightness.light),
```
If `BrightnessOption.dark`, set
```
c.CupertinoApp(
      initialRoute: '/username_add',
      title: "StarBook",
      theme: c.CupertinoThemeData(brightness: Brightness.dark),
```

Learn more from:
- https://api.flutter.dev/flutter/cupertino/CupertinoThemeData/brightness.html
- https://api.flutter.dev/flutter/widgets/MediaQueryData/platformBrightness.html
- https://api.flutter.dev/flutter/dart-ui/Window/onPlatformBrightnessChanged.html

Example:
https://github.com/hivedb/docs/blob/master/tutorials/dark_mode_switch.md

dependent on #160

**Comment by KhyatiSaini** [comment]
Sir, please assign me this issue
