### ISSUE TITLE
Add Feature to share mood 

### ISSUE THREAD

**Issue by spiderxm** [hashirshoaeb/star_book#172]
Add feature so user can share his mood for a particular day with other people.

**Comment by spiderxm** [comment]
Assign me this issue

**Comment by hashirshoaeb** [comment]
[Refining feature] 

Add a share icon, that allows you to copy or share the activity to other social media platforms. Or can also export as pdf.

**Comment by spiderxm** [comment]
ok will work on this

**Comment by hashirshoaeb** [comment]
I need time to refine it more. But if you want to work on it, go ahead. 🔥
