### ISSUE TITLE
username add sheet ui bug

### ISSUE THREAD

**Issue by 1hanzla100** [hashirshoaeb/star_book#173]
![Capture1](https://user-images.githubusercontent.com/59178380/106377140-acdb8080-63bc-11eb-8d64-a81a32602741.PNG)

**Comment by hashirshoaeb** [comment]
Kindly use the bug template to report bug. 

- mention screen size / device name
- your flutter version
- steps to reproduce

**Comment by 1hanzla100** [comment]
**Steps to Reproduce**
A RenderFlex overflowed by 32 pixels on the bottom.

**Code Sample**
```
Line 102 in ```screens\username_add_sheet.dart```
```
**Flutter Doctor Command**
```
Output
```
**Version**
 - Platform: Android Nexus 4 
 - Flutter version: [e.g. 1.22.2]

**Comment by 1hanzla100** [comment]
Making PR for it
![Capture1](https://user-images.githubusercontent.com/59178380/106378236-f203b080-63c4-11eb-96d3-1ba606fa13f3.PNG)

**Comment by hashirshoaeb** [comment]
okay

**Comment by hashirshoaeb** [comment]
[Notes:] Expanded and flex can be used. 

for ref:
- https://api.flutter.dev/flutter/widgets/Expanded-class.html
- https://www.youtube.com/watch?v=CI7x0mAZiY0

`flex` property will work as ratio

**Comment by hashirshoaeb** [comment]
fixed in 6084f19dd4f41b263e828522f44c87c7c4d7b0de
