### ISSUE TITLE
Year Page loads slowly

### ISSUE THREAD

**Issue by hashirshoaeb** [hashirshoaeb/star_book#176]
**Steps to Reproduce**
On navigate to year page from home page.

**Problem**
It opens the year page after some delay

I guess the problem is the 'for loop' that loads the 12 month widgets. 

One improvement that can be made is to make it infinite list.

**Comment by Imadarshsri** [comment]
I would like to work on this...

**Comment by hashirshoaeb** [comment]
@Imadarshsri any progress on it?
