### ISSUE TITLE
Make username editable

### ISSUE THREAD

**Issue by hashirshoaeb** [hashirshoaeb/star_book#177]
- In profile page, extract username into a separate widget. name it 'Username'
- Make a textfield and and a button to set/update the username, like the mockup below and name this widget as 'UsernameEdit'
- switch the widgets using this `AnimatedSwitcher`

Learn more from:
- https://www.youtube.com/watch?v=2W7POjFb88g

**Comment by hashirshoaeb** [comment]
<img  width="550"  src="https://user-images.githubusercontent.com/35165481/106391545-c78b1500-640f-11eb-9721-8b32a9f7dbf4.JPG" />

**Comment by KhyatiSaini** [comment]
Sir, please assign me this issue
