### ISSUE TITLE
Add gesture detectors to change calendar months.

### ISSUE THREAD

**Issue by hashirshoaeb** [hashirshoaeb/star_book#18]
Add swipe left/right gesture detectors to change calendar months.

**Comment by ShahzadUmarBaig** [comment]
We have to change the homepage coding as it is taking 10 2020 as parameters in Month widget, we have to acquire DateTime.Now to get the current month to display. After that we can use the Swipe left right gesture

**Comment by hashirshoaeb** [comment]
yea u are right, will do it later, with date.now to get the on going month and year. I did this because mock data that i wrote was for October, that's why I hardcoded it.
