### ISSUE TITLE
Add download icon

### ISSUE THREAD

**Issue by hashirshoaeb** [hashirshoaeb/star_book#184]
Add the `download  from the appstore` badge in Readme.
Choose the light one.

Follow the guidelines: https://developer.apple.com/app-store/marketing/guidelines/

Marketing tool: https://tools.applemediaservices.com/app/1552418289?country=us  

Ref: 
- https://tools.applemediaservices.com/

**Comment by spiderxm** [comment]
assign me this issue

**Comment by hashirshoaeb** [comment]
You are good to go. Make sure to use like the one i have used in the website. https://www.starbook.dev/
If you use file/image instead of link, then be sure to put that inside readme docs folder.

**Comment by hashirshoaeb** [comment]
if you got queries, feel free to ping me on slack.

**Comment by spiderxm** [comment]
sure
