### ISSUE TITLE
Shift the place of gifs

### ISSUE THREAD

**Issue by hashirshoaeb** [hashirshoaeb/star_book#185]
move the gifs from `assets` folder to `READMEdocs` and update the links in readme.

**Comment by hashirshoaeb** [comment]
Sure 🔥

**Comment by Vrushti24** [comment]
which links I have to update in readme ? @hashirshoaeb

**Comment by hashirshoaeb** [comment]
As we are using those gifs in Readme.md to showcase the android version. So the paths needs to be updated there as well.

**Comment by hashirshoaeb** [comment]
You can take example of how I added the path for IOS 

```
<img src="READMEdocs/demo-light.gif" width="320" ></img>
```

**Comment by Vrushti24** [comment]
okay thanks

**Comment by Vrushti24** [comment]
Done PR #199  please check that.

**Comment by hashirshoaeb** [comment]
Nicely done! Thank you for contributing.

**Comment by Vrushti24** [comment]
Thank u for ur support
