### ISSUE TITLE
grammar mistake

### ISSUE THREAD

**Issue by hashirshoaeb** [hashirshoaeb/star_book#190]
Fix the grammar mistake in [PRIVACY&POLICY.md](https://github.com/hashirshoaeb/star_book/blob/master/PRIVACY%26POLICY.md)

**Comment by 96RadhikaJadhav** [comment]
@hashirshoaeb Want to work on this too :).

**Comment by hashirshoaeb** [comment]
@96RadhikaJadhav any progress on it?

**Comment by 96RadhikaJadhav** [comment]
@hashirshoaeb  Will create a PR today.
