### ISSUE TITLE
floating action button

### ISSUE THREAD

**Issue by hashirshoaeb** [hashirshoaeb/star_book#193]
Add a floating action button in the HomePage in the bottom right corner.

See: [Screen 1](https://github.com/hashirshoaeb/star_book/blob/master/CONTRIBUTING.md#mock-up)

**Comment by ShrutiJ-01** [comment]
I would like to work on it

**Comment by hashirshoaeb** [comment]
Hey @ShrutiJ-01 let me know if you have any progress on it.

**Comment by hashirshoaeb** [comment]
All you need is to replace CupertinoScaffold  with `Scaffold` and use floading action property.  and on pressed, navigate it to the ActivityAddSheet, with DateTime.now().

**Comment by khushbooag4** [comment]
I want to work on this issue??

**Comment by hashirshoaeb** [comment]
> I want to work on this issue??

Sure go ahead. assigning issue to you :D

**Comment by samrath-sudesh-acharya** [comment]
Raised a pr , pls merge it
