### ISSUE TITLE
greeting relative to the time,

### ISSUE THREAD

**Issue by hashirshoaeb** [hashirshoaeb/star_book#194]
Update greeting in Profile page.
in morning, good morning etc
at night , good night. 
else Hi, hello etc

**Comment by spiderxm** [comment]
Assign me this issue

**Comment by spiderxm** [comment]
Assign me this issue

**Comment by hashirshoaeb** [comment]
Sorry i forgot that you previously claimed. And thanks for reminding me. Good luck
