### ISSUE TITLE
Spelling mistake

### ISSUE THREAD

**Issue by hashirshoaeb** [hashirshoaeb/star_book#197]
Correct the spells of February

**Comment by spiderxm** [comment]
assign me this issue

**Comment by vaishnavirshah** [comment]
can you assign me this issue please

**Comment by hashirshoaeb** [comment]
https://github.com/hashirshoaeb/star_book/blob/4f84cc2f8cce131e1f77666edb5d2c6250ab55c6/lib/utils/date.dart#L61

**Comment by 96RadhikaJadhav** [comment]
@hashirshoaeb Can I create a PR for this?

**Comment by hashirshoaeb** [comment]
yea sure.
