### ISSUE TITLE
Spelling mistake

### ISSUE THREAD

**Issue by hashirshoaeb** [hashirshoaeb/star_book#202]
add activity

https://github.com/hashirshoaeb/star_book/blob/4f84cc2f8cce131e1f77666edb5d2c6250ab55c6/lib/screens/activity_edit_sheet.dart#L119

**Comment by PrathameshAshra** [comment]
can you assign me this ?

**Comment by hashirshoaeb** [comment]
Sure

**Comment by PrathameshAshra** [comment]
Thanks, would get back to you and create a new PR in 2 days.

**Comment by hashirshoaeb** [comment]
hahaha! by the way it will take less than 5 minutes to fix this.

**Comment by hashirshoaeb** [comment]
No problem you can take time ❤️

**Comment by PrathameshAshra** [comment]
Hi @hashirshoaeb, I tied searching for the spelling error but unable to find any typos here.

**Comment by hashirshoaeb** [comment]
🤦🏻‍♂️ I've mentioned in the issue.

**Comment by hashirshoaeb** [comment]
> add activity
> 
> https://github.com/hashirshoaeb/star_book/blob/4f84cc2f8cce131e1f77666edb5d2c6250ab55c6/lib/screens/activity_edit_sheet.dart#L119

here
