### ISSUE TITLE
Background colour should not be black.

### ISSUE THREAD

**Issue by hashirshoaeb** [hashirshoaeb/star_book#23]
Meanwhile async call resolves the promise, background colour should not be black. It can be transparent.

**Comment by hashirshoaeb** [comment]
<img src="https://user-images.githubusercontent.com/35165481/95664551-64285f00-0b62-11eb-9aa0-8cb9ad6cf035.png" width=300 alt="Simulator Screen Shot - iPhone 11 Pro - 2020-10-11 at 01 33 18" ></img>

**Comment by ShahzadUmarBaig** [comment]
I will be fixing this issue today.
