### ISSUE TITLE
Change preference sheet to page.

### ISSUE THREAD

**Issue by hashirshoaeb** [hashirshoaeb/star_book#235]
change the bottom sheet to full page.

**Comment by noman2002** [comment]
Hey, please explain a bit more about the issue. I'm willing to work on this, please assign it.

**Comment by hashirshoaeb** [comment]
Hi, Thank you for taking interest. 

When you click hamburger, you will notice that it opens a bottom sheet. My naming conventions, I write bottoms sheets as (sheet) and full screen page as (page). So instead of open the preference screen as bottom sheet open it as full screen. 

You will also have to change the class name from "sheet" to "page" 

Hope this answers your query. feel free to ask further questions.

**Comment by noman2002** [comment]
OK Got it. will reach out to you if I have any trouble while fixing this.

**Comment by noman2002** [comment]
Sorry I am unable to fix this.

**Comment by hashirshoaeb** [comment]
> Sorry I am unable to fix this.

Oh Thank you for your time. Let me know if you need assistance in logic building, or code understanding. Or else I'll assign it to myself.
