### ISSUE TITLE
Export Data (a)

### ISSUE THREAD

**Issue by hashirshoaeb** [hashirshoaeb/star_book#236]
In preference page UI. Add a tile saying 'Export all data'

**Comment by atharv-bhadange** [comment]
Hey! I'm a beginner, can I work on this?
I'll add a `Privacy` tab under which there will be the required `Export all data` tile.

**Comment by hashirshoaeb** [comment]
sure, I'll create a mock UI for you. for better understanding. :)

**Comment by hashirshoaeb** [comment]
![image](https://user-images.githubusercontent.com/35165481/145670060-a5e8c8e6-1616-43ca-a864-f1d87062d9fb.jpeg)

**Comment by hashirshoaeb** [comment]
you can also work on #237 in a single PR. Task is just to implement UI with no (onPressed or onTap) logic.

**Comment by atharv-bhadange** [comment]
Will this do?

![image](https://user-images.githubusercontent.com/65965314/145687065-f93dca3e-a053-4b7c-a078-92acaa4abdba.png)

**Comment by hashirshoaeb** [comment]
yesss perfect
