### ISSUE TITLE
Make BaseController abstract and remove overridden method

### ISSUE THREAD

**Issue by ShrutiJ-01** [hashirshoaeb/star_book#241]
In base_controller.dart ,make  the BaseController class abstract and remove overridden method.

can you make it abstract class? 
`abstract class BaseController`

_Originally posted by @hashirshoaeb in https://github.com/hashirshoaeb/star_book/pull/240#discussion_r767229328_

we do not need to override this method, since you are only calling super here. so that does not make sense.

_Originally posted by @hashirshoaeb in https://github.com/hashirshoaeb/star_book/pull/240#r767229451_

**Comment by SharviE29** [comment]
Yes , I will make these changes
