### ISSUE TITLE
Add action sheet

### ISSUE THREAD

**Issue by hashirshoaeb** [hashirshoaeb/star_book#243]
[Cupertino action sheet](
https://api.flutter.dev/flutter/cupertino/CupertinoActionSheet-class.html)

![image](https://user-images.githubusercontent.com/35165481/146385941-0aeef33e-f082-4013-aecb-32fab904163b.png)

Task:

- [ ] In `ActivityPage` add a "vertical 3 dot icon" on the top right corner of the screen. 
- [ ] On tap to this icon, open `CupertinoActionSheet` with following tiles:
- [x] #244
- [ ] "Edit" on tap -> Navigate to ActivityEditSheet (just more the functionality that was on the top right corner previously) 
- [x] #245
- [ ] "Cancel" ontap -> navigator.pop (as explained in CupertinoActionSheet  docs 

ref links: 
- https://api.flutter.dev/flutter/cupertino/CupertinoActionSheet-class.html
- https://youtu.be/U-ao8p4A82k

**Comment by samrath-sudesh-acharya** [comment]
@hashirshoaeb assign this to me

**Comment by hashirshoaeb** [comment]
There you go 🚀
