### ISSUE TITLE
Route name refactoring

### ISSUE THREAD

**Issue by hashirshoaeb** [hashirshoaeb/star_book#246]
Currently all the routes and their names are defined in `RouteGenerator`. So for navigation I need to copy over the same route string. Where there is code duplication there is a chance of bugs. So to get rid of this situation i planned this refactoring task. 

We will create a static route string in the same screen widget and will access this variable in `RouteGenerator` and `Navigator`.
pseudo code
```dart
Class ScreenName extends StatelessWidget {
  static String routeName = '/route';
}
```
use
```dart
 case ScreenName .routeName:
        return MaterialWithModalsPageRoute(
          builder: (context) => ScreenName (),
        );
```
```dart
Navigator.of(context).pushNamed(
                      PackageSheet.routeName,
)
```

**Comment by samrath-sudesh-acharya** [comment]
raised a pr , please merge it
