### ISSUE TITLE
Create Github issue templates

### ISSUE THREAD

**Issue by hashirshoaeb** [hashirshoaeb/star_book#255]
Last time we did something like this: https://github.com/hashirshoaeb/star_book/issues/49
Here are the files you can copy them: https://github.com/hashirshoaeb/star_book/tree/old-master/.github/ISSUE_TEMPLATE

**Comment by SaumyaBhushan** [comment]
I would Like to work on this . Please assign it to me @hashirshoaeb

**Comment by SaumyaBhushan** [comment]
@hashirshoaeb Let me know if its work for you.
