### ISSUE TITLE
Create calendar

### ISSUE THREAD

**Issue by hashirshoaeb** [hashirshoaeb/star_book#288]
Create a logic for building calendar.

For reference you can visit old code. 

Month: https://github.com/hashirshoaeb/star_book/blob/old-master/lib/widgets/month.dart
Year:  https://github.com/hashirshoaeb/star_book/blob/old-master/lib/widgets/year.dart

I initially took the inspiration from here: https://github.com/mennorenkens/flutter_scrolling_calendar

These widgets are going to be the backbone of the app. create them well.

PS: DO NOT copy paste. understand how it works. because initial task is to build calendar, we will inject activity later.

**Comment by AbdullahAhmedSoomro** [comment]
- Code Pushed PR #293 UI Create Calendar.
- Bloc not implemented yet.
