### ISSUE TITLE
Define Paddings in theme

### ISSUE THREAD

**Issue by hashirshoaeb** [hashirshoaeb/star_book#305]
![Screenshot 2023-02-02 at 2 56 36 PM](https://user-images.githubusercontent.com/35165481/216292736-f63951a7-a9b1-4105-8ace-6a8096b9275d.png)

**Comment by AbdullahAhmedSoomro** [comment]
Padding is only from top and bottom, right?
Padding: EdgeInsets.only(top: 10, bottom: 10)

**Comment by hashirshoaeb** [comment]
I think just define paddings as double.

**Comment by hashirshoaeb** [comment]
then we will be able to use those variable in either Padding or SizeBox, it will be our choice.

**Comment by AbdullahAhmedSoomro** [comment]
I think we have to define default values in the ultramarine theme, which is not a problem, but the double data type is not The method 'lerp' isn't defined for the type 'double'.
