### ISSUE TITLE
Nested routing 

### ISSUE THREAD

**Issue by hashirshoaeb** [hashirshoaeb/star_book#31]
On poping the initial route of the inner navigator should take context to the outer navigator.

**Comment by hashirshoaeb** [comment]
<img src="https://user-images.githubusercontent.com/35165481/96342301-fc6a9a80-10b2-11eb-82ba-59dc2c5edb44.gif" alt="bug-nested-routing" width=200 />

**Comment by AseemWangoo** [comment]
Some thoughts

1. Instead of tapping the mood, try click on done?

Is the done button implementing .pop(context) ?

**Comment by hashirshoaeb** [comment]
yes button "done" has Navigator.of(context).pop()

**Comment by hashirshoaeb** [comment]
@AseemWangoo still give the same results

**Comment by jordanmlacalle** [comment]
@hashirshoaeb Raised PR, #32 , to resolve this issue.
