### ISSUE TITLE
Refactor Custom Text Form Field

### ISSUE THREAD

**Issue by AbdullahAhmedSoomro** [hashirshoaeb/star_book#332]
![image](https://user-images.githubusercontent.com/50518325/218946614-15ac9abc-8a6c-42ec-a498-4a26b7aefaaf.png)
 
![image](https://user-images.githubusercontent.com/50518325/218946576-2dd6049b-3748-4a5b-b303-cbe4501c67ad.png)

**Comment by hashirshoaeb** [comment]
![simulator_screenshot_D26A0C26-A6EC-4A36-9EB6-DC8A8CB00E10](https://user-images.githubusercontent.com/35165481/220121980-be25b1b8-2ad9-4cc7-a560-d0c286cf87ea.png)
