### ISSUE TITLE
Add animation on Horizontal Drag to left and right on home screen calendar. 

### ISSUE THREAD

**Issue by hashirshoaeb** [hashirshoaeb/star_book#34]
On changing state, widget should have some cool animation.

**Comment by sakshikhachane** [comment]
@hashirshoaeb I would like to work on this issue. Please assign me this issue.

**Comment by hashirshoaeb** [comment]
Under SWoC?

**Comment by sakshikhachane** [comment]
Yes

**Comment by hashirshoaeb** [comment]
kindly ping me on slack, and let me know how are you planning to solve this issue.

**Comment by sid-1207** [comment]
Hey I would like to resolve this issue
Please assign it to me
