### ISSUE TITLE
Preference Sheet

### ISSUE THREAD

**Issue by hashirshoaeb** [hashirshoaeb/star_book#35]
- [x] In Navigation Bar, instead of back icon, there should be "back" text. 
- [x] Should be in Cupertino style.
- [x] Compatible with dark mode .

**Comment by ShahzadUmarBaig** [comment]
What is this issue? Explain in detail.

**Comment by ShahzadUmarBaig** [comment]
I have fixed this issue, adding it directly to my master, you can review this and merge if you find it correct.
