### ISSUE TITLE
Screens Business Logic implementation

### ISSUE THREAD

**Issue by hashirshoaeb** [hashirshoaeb/star_book#372]
- [ ] Splash Screen
- [x] #401
- [ ] Year Screen
- [x] #403
- [x] #407
- [x] #405
- [ ] Settings Screen
- [ ] License Screen
- [x] #394
- [x] #397
- [x] #399
- [ ] Date Picker Screen 
- [ ] Create Mood Picker Screen

**Comment by AbdullahAhmedSoomro** [comment]
Baaqi Screens p to cubit ki zarort ni paregi

**Comment by hashirshoaeb** [comment]
Resources:
- https://bloclibrary.dev/#/
- https://www.youtube.com/watch?v=y564ETOCog8
- https://bloclibrary.dev/#/fluttertodostutorial
