### ISSUE TITLE
Changes Suggestion

### ISSUE THREAD

**Issue by ShahzadUmarBaig** [hashirshoaeb/star_book#40]
I have made a few changes in my fork, first I have changed the mood sheet text size back to default, it is extra big making it a little bolder, additionally I have changed the way circle colors are created, they are created using borderRadius previously where as I am using BoxShape.Circle which makes it perfectly circle without any radius, secondly I have change the padding to 8,8 that makes the circle smaller let me attach a screen shot, and finally I was able to fix the Activity edit sheet mood theme that is mentioned on the board, I have changed the container from ActionContainer to ColorContainer where the starting color is grey and once the user selects the color it returns back the selected color.

<img src="https://user-images.githubusercontent.com/59028228/97083806-203a5d00-162c-11eb-9c65-c15e9f4ff3b1.png" width =200 />
<img src="https://user-images.githubusercontent.com/59028228/97083808-216b8a00-162c-11eb-81b1-fc641690dd7a.png" width =200 />
<img src="https://user-images.githubusercontent.com/59028228/97083809-22042080-162c-11eb-956f-b9809300ecdb.png" width =200 />

**Comment by hashirshoaeb** [comment]
Hi, that sounds good. Create a pull request. Let me see your changes.

Thanks.
