### ISSUE TITLE
When clicking on Star book Community 

### ISSUE THREAD

**Issue by hashirshoaeb** [hashirshoaeb/star_book#463]
Here is a new link: https://discord.gg/7EJv8VUGrd

**Comment by gantanikhilraj** [comment]
Hey @hashirshoaeb , I would to work on this issue, can you assign this to me and also give me some more details on this issue.

**Comment by hashirshoaeb** [comment]
Done

**Comment by gantanikhilraj** [comment]
@hashirshoaeb , Can you explain me the what the issue is about ?

**Comment by gantanikhilraj** [comment]
I've submitted the PR, if any changes required please let me know.
