### ISSUE TITLE
Remove about developer section

### ISSUE THREAD

**Issue by hashirshoaeb** [hashirshoaeb/star_book#464]
![image](https://github.com/hashirshoaeb/star_book/assets/35165481/a6b2c7c0-06b1-4670-a2df-2b94f9ce274f)

**Comment by SunMoon97** [comment]
Hello,

I'm new to the field of open-source contribution and would appreciate some guidance on approaching the following issue.I haven't started working on this issue yet and I'd like to learn how to approach it effectively. Any advice or suggestions would be greatly appreciated. Thank you for your time and assistance!

Best regards,

**Comment by gantanikhilraj** [comment]
Hey @hashirshoaeb , I would like to work on this, please assign this to me.

**Comment by hashirshoaeb** [comment]
> Hello,
> 
> I'm new to the field of open-source contribution and would appreciate some guidance on approaching the following issue.I haven't started working on this issue yet and I'd like to learn how to approach it effectively. Any advice or suggestions would be greatly appreciated. Thank you for your time and assistance!
> 
> Best regards,

This may help. https://hacktoberfest.com/participation/

**Comment by gantanikhilraj** [comment]
@hashirshoaeb , I've submitted PR, if you need any changes please let me know.

**Comment by hashirshoaeb** [comment]
> @hashirshoaeb , I've submitted PR, if you need any changes please let me know.

Thanks man
