### ISSUE TITLE
Add year view

### ISSUE THREAD

**Issue by hashirshoaeb** [hashirshoaeb/star_book#47]
Need to implement year view screen that shows user, a scrollable year calendar with mood colors.    
Add a text button on the top left of the  homePage and Navigate to year view screen.  

- [x] YearPage
- [x] Year Widget 
- [x] Navigation Route to YearPage 

You can look into this https://github.com/mennorenkens/flutter_scrolling_calendar package to get the idea of implementation.

**Comment by cyber-venom003** [comment]
@hashirshoaeb Can you please assign it to me?? I'll start contributing it from 5th Jan

**Comment by hashirshoaeb** [comment]
Sure. Check (8) Screen here: [Starbook.pdf](https://github.com/hashirshoaeb/star_book/blob/master/READMEdocs/StarBook.pdf)

**Comment by hashirshoaeb** [comment]
https://github.com/mennorenkens/flutter_scrolling_calendar/blob/master/lib/year_view.dart

**Comment by hashirshoaeb** [comment]
@cyber-venom003 any progress? or facing issues?

**Comment by cyber-venom003** [comment]
> @cyber-venom003 any progress? or facing issues?
> 

Still working on it, was busy in some other stuff. Will try to raise a PR asap.👍

**Comment by hashirshoaeb** [comment]
year widget implementation in #92
