### ISSUE TITLE
Analytics Widget

### ISSUE THREAD

**Issue by hashirshoaeb** [hashirshoaeb/star_book#48]
Need to implement analytics widget, which shows monthly and weekly mood graph.
- [x]  Analytics Widget
- [ ]  Monthly Mood graph
- [ ] Weekly Mood  graph

For reference, look into https://reflectly.app/

**Comment by spiderxm** [comment]
I would like to work on this, please assign me this issue

**Comment by hashirshoaeb** [comment]
Go through [Contributing.md](https://github.com/hashirshoaeb/star_book/blob/master/CONTRIBUTING.md)

**Comment by KhyatiSaini** [comment]
Sir, I would like to work on this issue, please assign me this issue
