### ISSUE TITLE
Add GitHub Issue templates

### ISSUE THREAD

**Issue by hashirshoaeb** [hashirshoaeb/star_book#49]
Need to add following GitHub issue templates:
- [x] Bug Report
- [x] Feature Request
- [x] Question

You can take example reference from here: https://github.com/hivedb/hive/tree/master/.github/ISSUE_TEMPLATE

**Comment by Hardikkr** [comment]
You can assign this to me. And Can I work on more than one issue?

**Comment by hashirshoaeb** [comment]
Hi, I can see you excitement with SWoC. I suggest you to wait for 5th January. Then we will formerly start the contributing journey. 
I'm working on writing new issues and features.

**Comment by Hardikkr** [comment]
So, I have to make Github issue template the same as https://github.com/hivedb/hive/tree/master/.github/ISSUE_TEMPLATE this one?
I'll start working on this from 5th January.

**Comment by hashirshoaeb** [comment]
Yes

**Comment by hashirshoaeb** [comment]
try creating a new issue at hive https://github.com/hivedb/hive/issues
you will see how it works.
