### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by hashirshoaeb** [hashirshoaeb/star_book#50]
Need to add Notification Generation logic, So the app notifies user to add mood next morning if user forgets to add mood pervious day.

Add Setting option, and let the user tell when to remind him  to write diary. And generate notification at that time if user did not write diary.
 
- [x] Remind user to write todays diary.

**Comment by sid-1207** [comment]
Hey i would like to work on this issue
Please assign it to me

**Comment by mdmohsin7** [comment]
I would like to work on this issue. Can you please assign it to me?
