### ISSUE TITLE
Update gifs in Readme.md

### ISSUE THREAD

**Issue by hashirshoaeb** [hashirshoaeb/star_book#52]
Need to update gifs in Readme.md for 
 - [x] iOS or Android Phones
 - [x] Light and Dark Mode

This link https://ezgif.com/video-to-gif  will help your to convert screen recording to gif.

**Comment by shradhaagarwal01** [comment]
Sir, I am a participant in SWoC 2021. I would like to work on this issue.

**Comment by hashirshoaeb** [comment]
ping me on slack.

**Comment by kanishkaa24** [comment]
Can I work on this issue ?

**Comment by hashirshoaeb** [comment]
any updates?

**Comment by kanishkaa24** [comment]
Yes I'll complete it by today evening.

**Comment by hashirshoaeb** [comment]
You can convert your screen recording to gif from here, https://ezgif.com/video-to-gif

**Comment by kanishkaa24** [comment]
Hey
Can you guide me about installing flutter?
I have installed and extracted the folder but I'm not able to proceed further. 
Or if the app is on any app store, please share the link.

**Comment by hashirshoaeb** [comment]
@kanishkaa24 ping me on slack please.
