### ISSUE TITLE
Code Refactoring

### ISSUE THREAD

**Issue by hashirshoaeb** [hashirshoaeb/star_book#53]
Need to implement OOP concepts and design patterns to improve the quality, reusability and scalability of code.

- [x] Shift the state logic to the bloc pattern.

**Comment by mdmohsin7** [comment]
I would like to work on this issue. Can you please assign it to me?

**Comment by hashirshoaeb** [comment]
@mdmohsin7 Assigning you to work on bloc. I will discuss the architecture with you.

**Comment by mdmohsin7** [comment]
> @mdmohsin7 Assigning you to work on bloc. I will discuss the architecture with you. 

Oh okay 👍
