### ISSUE TITLE
Add steps to create git tag and github release

### ISSUE THREAD

**Issue by hashirshoaeb** [hashirshoaeb/star_book#533]
**Is your feature request related to a problem? Please describe.**
As we have planned to automate the deployment. Github release can be a nice trigger for production builds.

**Describe the solution you'd like**
we need to document how to create and push a git tag.

**Comment by dhirajchaurasiya** [comment]
Is it to be done in README.md file or CONTRIBUTING.md file?

**Comment by hashirshoaeb** [comment]
CONTRIBUTING.md

**Comment by dhirajchaurasiya** [comment]
@hashirshoaeb I have made few changes based on the issue addressed. Please Review
