### ISSUE TITLE
Add download on android button in readme

### ISSUE THREAD

**Issue by hashirshoaeb** [hashirshoaeb/star_book#536]
Play store link: https://play.google.com/store/apps/details?id=com.hashirshoaeb.StarBook

assets: https://play.google.com/intl/en_us/badges/

**Comment by Harish-2003** [comment]
Can u assign me this issue i can help it! @hashirshoaeb

**Comment by hashirshoaeb** [comment]
Sure

**Comment by Harish-2003** [comment]
do i need to make a pull request or do i need to commit directly to the dev branch here are the modifications that i have done and the resulted readme file looks like this  @hashirshoaeb 
![image](https://github.com/Blocship/star_book/assets/76206815/307eed4a-4bcc-40ff-a688-d8b69f0c4ae5)

**Comment by hashirshoaeb** [comment]
You can open a Pull request. Both badges should be aligned side by side in a single line/row

**Comment by hashirshoaeb** [comment]
Can we have both badges of same size?

**Comment by Harish-2003** [comment]
i tried doing that but those are not working.... wait lemee try it again

**Comment by Harish-2003** [comment]
![image](https://github.com/Blocship/star_book/assets/76206815/4a99413b-d431-43bc-bcb0-cbfa66d2dfb7)
i hope it's okay now?  @hashirshoaeb

**Comment by hashirshoaeb** [comment]
Thanks, but no. not in the table.

**Comment by hashirshoaeb** [comment]
Can you join [Starbook Discord](https://discord.gg/XQCQUdQc) to discuss?

**Comment by Harish-2003** [comment]
yea sure it's showing the link is invalid
@hashirshoaeb 
![image](https://github.com/Blocship/star_book/assets/76206815/4b1daa0c-90a1-48fb-8229-fbe8e2239135)
how about this

**Comment by hashirshoaeb** [comment]
Let me send new

**Comment by hashirshoaeb** [comment]
https://discord.gg/5rATmt2gvE

**Comment by Harish-2003** [comment]
i think we can close this issue now @hashirshoaeb

**Comment by hashirshoaeb** [comment]
Alignment is not correct. 
- [ ] both ios and andriod badges should be in a single line. and should have nearly same sizes.

**Comment by hashirshoaeb** [comment]
- https://stackoverflow.com/questions/34941473/new-google-play-badge-doesnt-get-the-size-right
- https://stackoverflow.com/questions/71708565/how-can-i-make-the-apple-store-and-google-play-store-badges-align-vertically

**Comment by hashirshoaeb** [comment]
- https://stackoverflow.com/questions/12090472/how-do-i-center-an-image-in-the-readme-md-file-on-github
