### ISSUE TITLE
Add Background Images

### ISSUE THREAD

**Issue by hashirshoaeb** [hashirshoaeb/star_book#55]
Need to add background images in home screen. Get a random wallpaper from unsplash using unplash APIs.

- [x] Implement Unsplash APIs
- [x] Show widget in the background of home screen
- [x] Show new image on swipe

You can look into: https://unsplash.com/developers

**Comment by ShrutiJ-01** [comment]
I would like to work on this issue If assigned under SWOC21

**Comment by hashirshoaeb** [comment]
Go through [Contributing.md](https://github.com/hashirshoaeb/star_book/blob/master/CONTRIBUTING.md)

**Comment by hashirshoaeb** [comment]
Things you need to do for now:

1. [ ] Looking into `.env` to securely save access key.
2. [ ] A constant/final variable to get `unsplash assess key `
3. [ ] A widget `UnsplashImage` that implements the api and return Image.

**Comment by ShrutiJ-01** [comment]
Yes, Will open a PR as soon as possible!
