### ISSUE TITLE
Date Picker Widget

### ISSUE THREAD

**Issue by hashirshoaeb** [hashirshoaeb/star_book#56]
Allow user to change date. Let user to select date through date picker widget. 
Note: Do not let user to pick a date on which mood is already done. And mood picker should be Cupertino style.  

- [ ] Add a 'add button' on home screen
- [ ] Implement date picker
- [ ] Edit date in add mood sheet

**Comment by spiderxm** [comment]
I would like to work on this, please assign me this issue.

**Comment by hashirshoaeb** [comment]
Go through [Contributing.md](https://github.com/hashirshoaeb/star_book/blob/master/CONTRIBUTING.md)
