### ISSUE TITLE
User Info Screen

### ISSUE THREAD

**Issue by hashirshoaeb** [hashirshoaeb/star_book#57]
Need to implement a screen to ask for username. Name it UsernameAddSheet

**Comment by ShrutiJ-01** [comment]
I would like to work on it!

**Comment by hashirshoaeb** [comment]
@ShrutiJ-01 I have assigned it to you. You can start working on it after 5th.

**Comment by ShrutiJ-01** [comment]
Thankyou! I'll start working on it after 5th👍

**Comment by hashirshoaeb** [comment]
Check (10) Screen here: [Starbook.pdf](https://github.com/hashirshoaeb/star_book/blob/master/READMEdocs/StarBook.pdf)

**Comment by ShrutiJ-01** [comment]
@hashirshoaeb I went through the wireframes, those were really helpful and beautiful! I wanted to know if I need to follow any color pallet as of now?

**Comment by hashirshoaeb** [comment]
Read  the rules in [Contributing.md ](https://github.com/hashirshoaeb/star_book/blob/master/CONTRIBUTING.md#rules)
Also have look into: https://developer.apple.com/design/human-interface-guidelines/ios/visual-design/color/
