### ISSUE TITLE
Bottom Navigation Bar

### ISSUE THREAD

**Issue by hashirshoaeb** [hashirshoaeb/star_book#58]
Need to implement, bottom tab bar consisting of two tabs, 
- [ ] homePage
- [ ] profilePage

You can learn from:
 - https://www.youtube.com/watch?v=3PdUaidHc-E
 - https://api.flutter.dev/flutter/cupertino/CupertinoTabBar-class.html

**Comment by prajakta2809** [comment]
i would like to work on it.

**Comment by hashirshoaeb** [comment]
@prajakta2809 wait for 5th Jan, then we will formally start our contributing journey.

**Comment by hashirshoaeb** [comment]
Tho I'm assigning it to you.

**Comment by hashirshoaeb** [comment]
@prajakta2809 please join starbook channel on slack

**Comment by hashirshoaeb** [comment]
Check 1 and 2 Screen, here: [Starbook.pdf](https://github.com/hashirshoaeb/star_book/blob/master/READMEdocs/StarBook.pdf)

**Comment by prajakta2809** [comment]
yes i will start working on it from 5th jan. And I had joined the channel.
