### ISSUE TITLE
Launch File

### ISSUE THREAD

**Issue by hashirshoaeb** [hashirshoaeb/star_book#59]
- [x] Add launch.json file for vscode. Add  default dart configurations.

You can learn from here: 
- https://flutter.dev/docs/development/tools/vs-code#run-app-in-debug-profile-or-release-mode

**Comment by Imadarshsri** [comment]
I would like to take this

**Comment by hashirshoaeb** [comment]
You can start contributing from 5th Jan.

**Comment by Imadarshsri** [comment]
Okay, I will start it by then.
