### ISSUE TITLE
Light And Dark Mode Switch

### ISSUE THREAD

**Issue by hashirshoaeb** [hashirshoaeb/star_book#60]
Need to implement  Dark mode switch in PreferenceSheet.

- [x] Three options: Auto, Light and Dark.

You may need to use bloc design. And You can also see CupertinoApp(), CupertinoThemeData() and brightness: Brightness widgets and enums in Cupertino package.

**Comment by KhyatiSaini** [comment]
Sir, I would like to work on it, please assign me this issue

**Comment by hashirshoaeb** [comment]
Check (9) Screen, here: [Starbook.pdf](https://github.com/hashirshoaeb/star_book/blob/master/READMEdocs/StarBook.pdf)

**Comment by KhyatiSaini** [comment]
Okay sir, thank you

**Comment by vilsi12** [comment]
can you assign me

**Comment by hashirshoaeb** [comment]
@vilsi12 You can with ask @KhyatiSaini. She is working on UI part of this issue.

**Comment by KhyatiSaini** [comment]
@vilsi12 ma'am I have added the switch button for dark mode in the PreferenceSheet, I'm not able to implement the bloc design, you can work on that

**Comment by hashirshoaeb** [comment]
@KhyatiSaini implement it like this. Like there are three options: Auto, Light and dark 

![IMG_0593](https://user-images.githubusercontent.com/35165481/103909045-084f8100-5125-11eb-8cb2-971263fec761.jpg)

**Comment by hashirshoaeb** [comment]
@KhyatiSaini check CupertinoSlidingSegmentedControl 
- https://flutter.dev/docs/development/ui/widgets/cupertino
- https://api.flutter.dev/flutter/cupertino/CupertinoSlidingSegmentedControl-class.html

**Comment by KhyatiSaini** [comment]
Okay sir
