### ISSUE TITLE
Update the deployment target of iOS version

### ISSUE THREAD

**Issue by infiniteoverflow** [hashirshoaeb/star_book#66]
When we run the app on iPhone 12 Pro Max Simulator , we get the following warning : 

`
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but
    the range of supported deployment target versions is 9.0 to 14.3.99. (in target
    'path_provider' from project 'Pods')
`

This can be resolved by changing the deployment target to something higher.

**Comment by infiniteoverflow** [comment]
SWOC '21 Participants Kindly comment on the issue if you are interested in working on this issue.

**Comment by hashirshoaeb** [comment]
https://stackoverflow.com/questions/63056454/xcode-12-deployment-target-warnings-when-use-cocoapods

**Comment by hashirshoaeb** [comment]
fixed in https://github.com/hashirshoaeb/star_book/commit/b693afc449a1081c69c6192d3d8b7ee6b5050600
