### ISSUE TITLE
Showing message when date is inactive

### ISSUE THREAD

**Issue by HimeshNayak** [hashirshoaeb/star_book#70]
**Is your feature request related to a problem? Please describe.**
The user does not get any message from the app stating that he cannot add the mood on that day.

**Describe the solution you'd like**
A Snackbar can be displayed to the user stating him that he cannot add moods in the future.

**Describe alternatives you've considered**
Any other widget can be shown too such as alertDialog, etc.

I would like to work on this issue. Please assign it to me under SWoC.

**Comment by hashirshoaeb** [comment]
Try looking for looking for iOS style dialog or snack bar. CupertinoDialog would work i guess.
