### ISSUE TITLE
Add mock data for testing purpose

### ISSUE THREAD

**Issue by hashirshoaeb** [hashirshoaeb/star_book#71]
- [ ] Create a list of activities in lib/models/activity.dart
- [ ] write a static 'initialize' method. check if hive is empty then populate it with mock data in list.
- [ ] call the initialize method in main

**Comment by Imadarshsri** [comment]
I would like to work on this.

**Comment by hashirshoaeb** [comment]
avoid filling activity with `lorem ipsum text`. Write some real type diary text, including words that express emotions like 'happy, glad, sad' etc. we will be needing this future.
