### ISSUE TITLE
Add User Model

### ISSUE THREAD

**Issue by hashirshoaeb** [hashirshoaeb/star_book#73]
```
class User {
  String name;
}
```
Take example from: [activiity.dart](https://github.com/hashirshoaeb/star_book/blob/master/lib/models/activity.dart) and [mood.dart](https://github.com/hashirshoaeb/star_book/blob/master/lib/models/mood.dart)

**Comment by KhyatiSaini** [comment]
Sir, I would like to work on this, please assign me this issue
