### ISSUE TITLE
Add Profile Page

### ISSUE THREAD

**Issue by hashirshoaeb** [hashirshoaeb/star_book#75]
Implement ProfilePage Screen
- [ ] Greetings widget
- [ ] Username widget
- [ ] Stats widget

For reference, check  Screen(2) [link](https://github.com/hashirshoaeb/star_book/blob/master/CONTRIBUTING.md#mock-up)

**Comment by Imadarshsri** [comment]
I would like to work on this.

**Comment by ShrutiJ-01** [comment]
I would like to work on it

**Comment by cyber-venom003** [comment]
@hashirshoaeb Can you please assign this to me? I would like to work on this.

**Comment by hashirshoaeb** [comment]
@ShrutiJ-01 please help him with UI.

**Comment by ShrutiJ-01** [comment]
Sure👍
