### ISSUE TITLE
Add route for UsernameAddSheet

### ISSUE THREAD

**Issue by hashirshoaeb** [hashirshoaeb/star_book#76]
- [x] you need to add route for UsernameAddSheet in [route_generator.dart](https://github.com/hashirshoaeb/star_book/blob/master/lib/routes/route_generator.dart)
-  [ ] if app launches first time show UsernameAddSheet before HomePage.
- [x] onContinue go to  HomePage.
- [ ]  if name is already filled skip UsernameAddSheet and directly show HomePage.

**Comment by ShrutiJ-01** [comment]
I would like to work on it

**Comment by hashirshoaeb** [comment]
Let me know when you start working on it.

**Comment by cyber-venom003** [comment]
@hashirshoaeb Is this issue yet to be closed??

**Comment by hashirshoaeb** [comment]
There are few things that are left. but we need hive integration before that. I'll be opening new issues for that next week probably.

**Comment by hashirshoaeb** [comment]
Remaining task in new issue #153
