### ISSUE TITLE
Add a splash screen for android

### ISSUE THREAD

**Issue by HimeshNayak** [hashirshoaeb/star_book#88]
Adding a splash screen for android

**Comment by hashirshoaeb** [comment]
Can you explain it a bit?

**Comment by suhas-kadu** [comment]
I would like solve this issue.

**Comment by suhas-kadu** [comment]
> Can you explain it a bit?

When an app is opened white screen is displayed initially and then the first screen. By adding a Splash screen this white screen can be eliminated. A png image has to added for splash screen

**Comment by HimeshNayak** [comment]
You can visit this link for more info.
https://flutter.dev/docs/development/ui/advanced/splash-screen
I would like work on this issue.

**Comment by Vrushti24** [comment]
I would like to work on this issue please assign me

**Comment by hashirshoaeb** [comment]
I looked into it. Since i have not designed logo for the splash screen yet. And if i had i would prefer to implement it for ios first. Thank you for suggesting the issue. I'm closing it for now. I'll reopen it in future.
