### ISSUE TITLE
Write guideline about adding .env

### ISSUE THREAD

**Issue by hashirshoaeb** [hashirshoaeb/star_book#98]
write guideline about adding .env file in project under getting started heading.

Ref:
https://pub.dev/packages/flutter_dotenv
https://github.com/hashirshoaeb/star_book#getting-started

**Comment by ShrutiJ-01** [comment]
I'd like to work on it!

**Comment by hashirshoaeb** [comment]
- comment out .env in pubspec.yml  https://github.com/hashirshoaeb/star_book/blob/master/pubspec.yaml#L73
- add in guideline:
  - uncomment it .env in pubspec.yml.
  - and add .env file
  - get client_id from unsplash by creating developer account
  - add in .env like that 
       ```
           CLIENT_ID=<your-client_id>
       ```

This is a rough idea. you can write in your words.
